EWPP-750: Description List paragraph.
openeuropa/oe_paragraphs pull request #124
Opened 2021-02-17 14:26 UTC by 22Alexandra

2021-02-22 11:36 UTC, sergepavle reviewed
I've left tiny comment

2021-02-22 11:36 UTC, sergepavle commented on modules/oe_paragraphs_description_list/README.md
> +This module provides Description List paragraph that depends on the [OpenEuropa Content Description List Field](https://github.com/openeuropa/oe_content/modules/oe_content_description_list_field)
The link is not updated.

2021-02-22 11:41 UTC, sergepavle submitted a review, later dismissed

2021-02-24 10:09 UTC, imanoleguskiza requested changes

2021-02-24 10:09 UTC, imanoleguskiza commented on modules/oe_paragraphs_description_list/config/install/field.field.paragraph.oe_description_list.field_oe_description_list_items.yml
> +translatable: false
This field needs to be translatable.

2021-02-24 10:09 UTC, imanoleguskiza commented on tests/features/description-list.feature
> +  so I can display an Overview.
"so I can display a list of term/description pairs." or something like that.

2021-02-24 10:54 UTC, imanoleguskiza approved these changes

2021-02-24 10:56 UTC, imanoleguskiza submitted a review, later dismissed

2021-02-24 11:12 UTC, sergepavle approved these changes

2021-02-24 14:10 UTC, upchuk requested changes

2021-02-25 08:21 UTC, sergepavle submitted a review, later dismissed

2021-02-26 12:41 UTC, upchuk requested changes

2021-02-26 12:41 UTC, upchuk commented on modules/oe_paragraphs_description_list/src/Plugin/Validation/Constraint/RequiredFields.php
> + *   id = "oe_paragraphs_description_list_required_fields",
Constraint IDs are typically CamelCase with first word caps as well. Check other existing ones please.

2021-02-26 12:41 UTC, upchuk commented on modules/oe_paragraphs_description_list/src/Plugin/Validation/Constraint/RequiredFields.php
> +class RequiredFields extends Constraint {
DescriptionListRequiredFields

2021-02-26 17:06 UTC, sergepavle approved these changes

2021-03-11 11:47 UTC, upchuk approved these changes

2021-03-23 08:39 UTC, merged