EWPP-811: Add optional heading field to Timeline paragraph.
openeuropa/oe_paragraphs pull request #125
Opened 2021-03-12 15:03 UTC by 22Alexandra

2021-03-15 12:38 UTC, upchuk requested changes

2021-03-15 12:38 UTC, upchuk commented on modules/oe_paragraphs_timeline/oe_paragraphs_timeline.post_update.php
> +  $entity_type = $config_manager->getEntityTypeIdByName($field_config);
Don't you know the entity type?

2021-03-15 12:38 UTC, upchuk commented on modules/oe_paragraphs_timeline/oe_paragraphs_timeline.post_update.php
> +  $entity = $entity_storage->createFromStorageRecord($config_record);
Let's also check if a field called "oe_title" doesnt exist already.

2021-03-15 13:13 UTC, upchuk requested changes
Accepting but keeping the PR blocked until the epic is ready to be merged.

2021-03-17 17:04 UTC, sergepavle approved these changes

2021-03-25 12:39 UTC, upchuk approved these changes

2021-03-25 12:44 UTC, sergepavle approved these changes

2021-03-25 12:44 UTC, merged