EWPP-1563: Adds optional Introduction field to Timeline paragraph.
openeuropa/oe_paragraphs pull request #157
Opened 2022-01-24 12:14 UTC by 22Alexandra

2022-01-24 18:28 UTC, nagyad requested changes

2022-01-24 18:28 UTC, nagyad commented on modules/oe_paragraphs_timeline/oe_paragraphs_timeline.post_update.php
> +  $field_config_storage = \Drupal::entityTypeManager()->getStorage('field_config');
This variable is kind off useless, not being used afterwards just once.

2022-01-24 18:28 UTC, nagyad commented on modules/oe_paragraphs_timeline/oe_paragraphs_timeline.post_update.php
> +  $field = FieldConfig::load($config_record['id']);
We know the id, why not to be explicit? So you don't need to load up $config_record variable just yet, just to check if the field exists already or not, would be better to load up the config once we are going to use it.

2022-01-25 15:34 UTC, nagyad submitted a review, later dismissed

2022-01-26 14:36 UTC, nagyad approved these changes

2022-01-27 10:25 UTC, upchuk approved these changes

2022-02-02 08:30 UTC, nagyad submitted a review, later dismissed

2022-03-15 08:09 UTC, upchuk approved these changes

2022-03-15 08:10 UTC, sergepavle approved these changes

2022-03-15 08:11 UTC, merged