EWPP-1865: Add Av Portal photo to illustration item image.
openeuropa/oe_paragraphs pull request #160
Opened 2022-01-31 12:36 UTC by yenyasinn

2022-02-01 14:15 UTC, sergepavle submitted a review, later dismissed

2022-02-24 08:49 UTC, upchuk approved these changes

2022-02-24 08:54 UTC, upchuk requested changes

2022-02-24 08:54 UTC, upchuk commented on modules/oe_paragraphs_illustrations_lists/config/install/field.field.paragraph.oe_illustration_item_image.field_oe_media.yml
> +    auto_create_bundle: av_portal_photo
Why is avportal in the auto_create?

2022-02-24 08:58 UTC, upchuk approved these changes

2022-02-24 08:59 UTC, brummbar approved these changes
Blind

2022-02-24 09:07 UTC, merged