EWPP-2018: Add Highlighted field for Text with featured Media paragraph.
openeuropa/oe_paragraphs pull request #164
Opened 2022-02-28 16:34 UTC by 22Alexandra

2022-03-02 12:03 UTC, sergepavle requested changes

2022-03-02 12:03 UTC, sergepavle commented on modules/oe_paragraphs_media/oe_paragraphs_media.post_update.php
> + * Add Highlighted field to Text with featured Media paragraph.
```suggestion
 * Add Highlighted field to Text with Featured media paragraph.
```

2022-03-02 12:03 UTC, sergepavle commented on modules/oe_paragraphs_media/oe_paragraphs_media.post_update.php
> +  $config = [
```suggestion
  $configs = [
```

2022-03-02 12:03 UTC, sergepavle commented on modules/oe_paragraphs_media/oe_paragraphs_media.post_update.php
> +  foreach ($config as $config_id) {
```suggestion
  foreach ($configs as $config_id) {
```

2022-03-02 14:05 UTC, sergepavle approved these changes

2022-03-03 12:29 UTC, yenyasinn commented on modules/oe_paragraphs_media/config/install/field.storage.paragraph.field_oe_highlighted.yml
> +translatable: true
```suggestion
translatable: false
```

2022-03-03 12:29 UTC, yenyasinn commented on modules/oe_paragraphs_media/config/post_updates/00004_highlighted_field/field.storage.paragraph.field_oe_highlighted.yml
> +translatable: true
```suggestion
translatable: false
```

2022-03-03 12:29 UTC, yenyasinn commented on modules/oe_paragraphs_media/oe_paragraphs_media.post_update.php
> +  $storage = new FileStorage(drupal_get_path('module', 'oe_paragraphs_media') . '/config/post_updates/00004_highlighted_field');
```suggestion
  $storage = new FileStorage(\Drupal::service('extension.list.module')->getPath('oe_paragraphs_media') . '/config/post_updates/00004_highlighted_field');
```
`drupal_get_path` is deprecated.

2022-03-09 07:49 UTC, yenyasinn commented on modules/oe_paragraphs_media/oe_paragraphs_media.post_update.php
> +  $storage = new FileStorage(drupal_get_path('module', 'oe_paragraphs_media') . '/config/post_updates/00004_highlighted_field');
It works in D9.2 but no need to rewrite later. It is already used in other components and ewcms

2022-03-11 10:49 UTC, yenyasinn submitted a review, later dismissed

2022-03-14 15:24 UTC, sergepavle submitted a review, later dismissed

2022-03-22 09:24 UTC, sergepavle approved these changes

2022-03-22 09:30 UTC, upchuk approved these changes
Blind

2022-03-22 09:30 UTC, merged