EWPP-2108: Add Carousel paragraph.
openeuropa/oe_paragraphs pull request #169
Opened 2022-04-11 12:59 UTC by 22Alexandra

2022-04-12 09:46 UTC, nagyad requested changes

2022-04-12 09:46 UTC, nagyad commented on modules/oe_paragraphs_carousel/config/install/field.storage.paragraph.field_oe_carousel_items.yml
> +translatable: true
This should not be translatable.

2022-04-12 09:46 UTC, nagyad commented on modules/oe_paragraphs_carousel/config/install/field.field.paragraph.oe_carousel_item.field_oe_media.yml
> +translatable: true
Why is this translatable?

2022-04-19 08:23 UTC, imanoleguskiza approved these changes

2022-04-19 10:37 UTC, nagyad approved these changes

2022-04-19 10:37 UTC, merged