EWPP-2426: Enable 'Description' field for 'Listing item' thumbnail primary variant.
openeuropa/oe_paragraphs pull request #183
Opened 2022-07-27 13:05 UTC by 22Alexandra

2022-07-29 16:40 UTC, sergepavle submitted a review, later dismissed

2022-08-10 13:15 UTC, nagyad submitted a review, later dismissed

2022-08-30 06:57 UTC, upchuk requested changes

2022-08-30 06:57 UTC, upchuk commented on oe_paragraphs.post_update.php
> +function oe_paragraphs_post_update_10010(): void {
Let's not do the post update here since it will put the field on for all the sites and it won't do anything for them. Let's move it to ewcms pls.

2022-08-30 07:49 UTC, upchuk approved these changes

2022-08-30 07:50 UTC, nagyad approved these changes

2022-08-30 07:50 UTC, merged