EWPP-3270: Add new fields to Banner paragraph.
openeuropa/oe_paragraphs pull request #197
Opened 2023-04-24 16:19 UTC by 22Alexandra

2023-05-02 14:30 UTC, sergepavle submitted a review, later dismissed

2023-05-12 07:52 UTC, imanoleguskiza requested changes
We need a Readme entry explaining the changes

2023-05-12 07:52 UTC, imanoleguskiza requested changes
We need a Readme entry explaining the changes

2023-05-15 07:44 UTC, imanoleguskiza approved these changes

2023-05-15 07:50 UTC, sergepavle approved these changes

2023-05-15 07:54 UTC, merged