EWPP-4984: Deprecated the Social feed paragraph.
openeuropa/oe_paragraphs pull request #238
Opened 2024-12-16 15:23 UTC by 22Alexandra

2024-12-17 10:25 UTC, nagyad submitted a review, later dismissed

2024-12-18 10:07 UTC, sergepavle approved these changes

2025-01-14 08:57 UTC, upchuk requested changes

2025-01-14 08:57 UTC, upchuk commented on tests/features/social-feed.feature
> +    And I press "Add Social feed - Deprecated"
1. If this paragraph type is no longer supported, why are we still testing it?
2. We put validation in oe_media that prevents you creating this media Shouldn't we do the same here? Put a validation that if you create a paragraph of this type, it won't allow you to do so. Or better yet, did you try removing this paragraph type from the list of selectable paragraphs at the field level? After a quick try, it seems to do the trick. The next time the user edits the node and tries to save it, they are informed they cannot reference that paragraph and they will have to remove it. And they won't have it in the selectable choices of paragraphs.

2025-01-14 13:41 UTC, 22Alexandra commented on tests/features/social-feed.feature
> +    And I press "Add Social feed - Deprecated"
1. Because we usually first mark features or entities as deprecated an remove them in a future release.
2. There is no validation in oe_media, the Webtools social feed media type is still available but marked as deprecated and new items can no longer be created because the "smk" services has been removed from oe_webtools.

2025-01-14 14:00 UTC, upchuk commented on tests/features/social-feed.feature
> +    And I press "Add Social feed - Deprecated"
@22Alexandra 1. yes, but this is not working in webtools anymore. So why spend resources in testing it if anyway nobody can actually use it anymore?

2025-02-03 09:38 UTC, 22Alexandra commented on tests/features/social-feed.feature
> +    And I press "Add Social feed - Deprecated"
Right, I removed the test.

2025-02-04 11:51 UTC, nagyad approved these changes

2025-02-04 11:51 UTC, merged